version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: thuyhip99
      MYSQL_DATABASE: inventory_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - inventory-net

  inventory_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-management
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "8090:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: thuyhip99
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_ELASTICSEARCH_USERNAME: elastic
      SPRING_ELASTICSEARCH_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8089
    networks:
      - inventory-net

volumes:
  mysql_data:

networks:
  inventory-net:
